import React from 'react'

type ContactEmailTemplateProps = {
    name: string
    email: string
    phone: string
    message: string
}

const ContactEmailTemplate = ({
    name,
    email,
    phone,
    message,
}: ContactEmailTemplateProps) => {
    return (
        <div
            style={{
                fontFamily: 'Arial, sans-serif',
                fontSize: '16px',
                color: '#333',
            }}
        >
            <h2 style={{ color: '#E60023' }}>New Inquiry Received</h2>

            <p>
                <strong>Name:</strong> {name}
            </p>
            <p>
                <strong>Email:</strong> {email}
            </p>
            <p>
                <strong>Phone:</strong> {phone}
            </p>
            <p>
                <strong>Message:</strong>
                <br />
                <span style={{ whiteSpace: 'pre-line' }}>{message}</span>
            </p>

            <hr
                style={{
                    margin: '20px 0',
                    border: 'none',
                    borderTop: '1px solid #ddd',
                }}
            />

            <p style={{ fontSize: '12px', color: '#777' }}>
                This email was automatically generated by the Virtual Rival
                website contact form.
            </p>
        </div>
    )
}

export default ContactEmailTemplate
